dist: trusty
language: java
jdk: oraclejdk8
addons:
    sonarcloud:
      organization: "vaidasbrazd"
      token:
        secure: "6ae7a3473808736b604e12f1b1df449476436562" # encrypted value of your token
  
        script:
            - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
            - if [ "$JAVA_HOME" = "/usr/lib/jvm/java-1.11.0-openjdk-amd64" ]; then mvn sonar:sonar; fi
            # end of file